[request_definition]
r = sub, project, resource, action

[policy_definition]
p = role, project, resource, action, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.role, r.project) && (p.project == "*" || p.project == r.project) && (p.resource == "*" || keyMatch2(r.resource, p.resource)) && (p.action == "*" || p.action == r.action)
